# Generated by Django 5.1.1 on 2024-09-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order_rename_oderitem_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanttity',
            new_name='quantity',
        ),
    ]
