# Generated by Django 5.1.1 on 2024-09-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_order_shipping_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
    ]
